import type { Metadata } from "next";
import { Anek_Gujarati } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "./globals.css";

config.autoAddCss = false;

const anekGujarati = Anek_Gujarati({
  subsets: ["latin"],
  variable: "--font-anek-gujarati",
});

export const metadata: Metadata = {
  title: "Lauren Easter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anekGujarati.variable} antialiased`}>{children}</body>
    </html>
  );
}
